services:
  marketplace-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: student_marketplace
    networks:
      - marketplace

networks:
  marketplace: